server:
  port: 9093
  servlet:
    context-path: /api/

spring:
  profiles:
    active: postgres

  liquibase:
    enabled: true
  messages:
    basename: messages

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    liquibase: INFO
    org:
      springframework: INFO
