spring:
  kafka:
    bootstrap-servers:      localhost:9092
    consumer:
      group-id:             notification-service-consumer
      key-deserializer:     org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:   org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset:    earliest
      enable-auto-commit:   false
    producer:
      acks:                 all
      retries:              3
      key-serializer:       org.apache.kafka.common.serialization.StringSerializer
      value-serializer:     org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
      concurrency:          3
    topic:
      name:
        ride-requests:      ride-requests
        available-drivers:  available-drivers
